[tools]
python = "3.10"
uv = "latest"

[settings]
experimental = true
python.uv_venv_auto = true

[hooks]
postinstall = "uv sync --extra cli"

[tasks]
check = [
  "uv sync --extra cli",
  "black --check .",
  "ruff check",
  "mypy",
  "pytest",
]
